/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package com.personnel.viewer;

import java.util.List;
import javax.persistence.EntityManager;
import javax.persistence.Persistence;
import javax.persistence.Query;
import org.netbeans.api.settings.ConvertAsProperties;
import org.openide.awt.ActionID;
import org.openide.awt.ActionReference;
import org.openide.explorer.ExplorerManager;
import org.openide.explorer.ExplorerUtils;
import org.openide.nodes.Children;
import org.openide.windows.TopComponent;
import org.openide.util.NbBundle.Messages;
import smls.AccessInfo;

/**
 * Top component which displays something.
 */
@ConvertAsProperties(
        dtd = "-//com.personnel.viewer//PersonnelSubystemViewer//EN",
        autostore = false
)
@TopComponent.Description(
        preferredID = "PersonnelSubystemViewerTopComponent",
        //iconBase="SET/PATH/TO/ICON/HERE", 
        persistenceType = TopComponent.PERSISTENCE_ALWAYS
)
@TopComponent.Registration(mode = "explorer", openAtStartup = true)
@ActionID(category = "Window", id = "com.personnel.viewer.PersonnelSubystemViewerTopComponent")
@ActionReference(path = "Menu/Window" /*, position = 333 */)
@TopComponent.OpenActionRegistration(
        displayName = "#CTL_PersonnelSubystemViewerAction",
        preferredID = "PersonnelSubystemViewerTopComponent"
)
@Messages({
    "CTL_PersonnelSubystemViewerAction=PersonnelSubystemViewer",
    "CTL_PersonnelSubystemViewerTopComponent=PersonnelSubystemViewer Window",
    "HINT_PersonnelSubystemViewerTopComponent=This is a PersonnelSubystemViewer window"
})
public final class PersonnelSubystemViewerTopComponent extends TopComponent implements ExplorerManager.Provider {

    private static ExplorerManager em = new ExplorerManager();

    public PersonnelSubystemViewerTopComponent() {
        initComponents();
        setName(Bundle.CTL_PersonnelSubystemViewerTopComponent());
        setToolTipText(Bundle.HINT_PersonnelSubystemViewerTopComponent());
        setVisible(false);
        EntityManager entityManager = Persistence.createEntityManagerFactory("PersonnelSubsystemLibraryPU").createEntityManager();
        Query query = entityManager.createNamedQuery("AccessInfo.findAll");
        List<AccessInfo> resultList = query.getResultList();
        em.setRootContext(new AccessInfoRootNode(Children.create(new AccessInfoChildFactory(resultList), true)));
        associateLookup(ExplorerUtils.createLookup(em, getActionMap()));
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        beanTreeView1 = new org.openide.explorer.view.BeanTreeView();

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(beanTreeView1, javax.swing.GroupLayout.DEFAULT_SIZE, 276, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(beanTreeView1, javax.swing.GroupLayout.PREFERRED_SIZE, 472, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );
    }// </editor-fold>//GEN-END:initComponents

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private org.openide.explorer.view.BeanTreeView beanTreeView1;
    // End of variables declaration//GEN-END:variables
    @Override
    public void componentOpened() {
        // TODO add custom code on component opening
    }

    @Override
    public void componentClosed() {
        // TODO add custom code on component closing
    }

    void writeProperties(java.util.Properties p) {
        // better to version settings since initial version as advocated at
        // http://wiki.apidesign.org/wiki/PropertyFiles
        p.setProperty("version", "1.0");
        // TODO store your settings
    }

    void readProperties(java.util.Properties p) {
        String version = p.getProperty("version");
        // TODO read your settings according to their version
    }

    @Override
    public ExplorerManager getExplorerManager() {
        return em;
    }

    public static void refreshNode() {
        EntityManager entityManager = Persistence.createEntityManagerFactory("PersonnelSubsystemLibraryPU").createEntityManager();
        Query query = entityManager.createNamedQuery("AccessInfo.findAll");
        List<AccessInfo> resultList = query.getResultList();
        em.setRootContext(new AccessInfoRootNode(Children.create(new AccessInfoChildFactory(resultList), true)));
    }
}
